### ISSUE TITLE
Warnings in Docker build

### ISSUE THREAD

**Issue by dsperling** [smithmicro/mapbox-gl-circle#65] opened 2017-12-08 23:30 UTC
Running Docker build:

`docker build -t circle .`

produces warnings on Step 4/8:
```
...
Step 4/8 : RUN npm install && mkdir -p example/ lib/
 ---> Running in 88bdb9b71fdb
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated yarn@0.27.5: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN deprecated mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm WARN lifecycle mapbox-gl-circle@1.6.3~prepare: cannot run in wd %s %s (wd=%s) mapbox-gl-circle@1.6.3 mkdir -p dist && browserify --standalone MapboxCircle -t [ babelify --presets [ es2015 ] ] lib/main.js | uglifyjs -c -m > dist/mapbox-gl-circle-${BUILD_VERSION:-dev}.min.js && cp -f dist/mapbox-gl-circle-${BUILD_VERSION:-dev}.min.js dist/mapbox-gl-circle.min.js /opt/mapbox-gl-circle
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
...
```
We should get these cleaned up to produce a clean Docker image.

**Comment by mblomdahl** [comment] 2022-10-23 14:34
I think the root cause of the severe warnings (and sometimes errors) are `fsevents` and other _`optionalDependencies`_ addressed in issue #82, merging in #84 should resolve these. However, we still have a bunch of warnings due to outdated 5+ years old NPM dependencies... But let's address these elsewhere!

**Closed as completed** 2022-10-23 14:53 UTC
Labels: help wanted, dependencies
